import type { EvidenceReference, SkillArtifact, TaskRunListItem, TaskRunResponse, TemplateSummary } from "./types";

const basePrompt =
  "Perform a financial audit for Invisium FY2026 using the uploaded financial statements and supporting evidence.";

function demoEvidence(documentId: string): EvidenceReference {
  return {
    id: `${documentId}_chunk_0`,
    document_id: documentId,
    document_name: documentId,
    chunk_id: `${documentId}_chunk_0`,
    page: null,
    char_start: 0,
    char_end: 120,
    retrieval_score: 0.91,
    support_level: "direct",
    citation_mode: "direct",
    source_type: "retrieved",
    text_excerpt: "",
    metadata: {},
  };
}

function demoNodeMetadata(column: number, row: number, demoExplanation: string) {
  return {
    layout: { column, row },
    demo_explanation: demoExplanation,
  };
}

export const mockTask: TaskRunResponse = {
  task_id: "demo-task",
  prompt: basePrompt,
  template_id: "perform_a_financial_audit_for_invisium_fy_template",
  program_id: "perform_a_financial_audit_for_invisium_fy_v1",
  program_version: "1.0.0",
  domain: "financial audit",
  deterministic: true,
  determinism_mode: "best_effort_deterministic",
  control_level: "operational",
  default_visibility_tier: "structured_reasoning_trace",
  model_id: "demo-provider",
  model_version: "demo-provider",
  provider_fingerprint: "demo-fingerprint",
  execution_endpoint: "https://demo-provider.local/chat/completions",
  prompt_hash: "demo-prompt-hash",
  grs_hash: "demo-grs-hash",
  execution_env_hash: "demo-env-hash",
  reproducibility_hash: "demo-repro-hash",
  status: "completed",
  created_at: new Date().toISOString(),
  completed_at: new Date().toISOString(),
  source_documents: [
    {
      id: "doc_charter",
      name: "audit_charter.txt",
      media_type: "text/plain",
      storage_path: "",
      text_path: "",
      sha256: "demo",
      extracted_text: "Entity: Invisium\nFiscal year: FY2026\nAudit objective: External financial statement audit.",
      metadata: {},
    },
    {
      id: "doc_controls",
      name: "controls_and_compliance.txt",
      media_type: "text/plain",
      storage_path: "",
      text_path: "",
      sha256: "demo",
      extracted_text:
        "Revenue cutoff observations: Twelve invoices totaling USD 214500 were recognized before shipment.",
      metadata: {},
    },
    {
      id: "doc_financials",
      name: "financial_statements_excerpt.txt",
      media_type: "text/plain",
      storage_path: "",
      text_path: "",
      sha256: "demo",
      extracted_text:
        "Revenue: 12.5m\nNet income: 0.61m\nMateriality benchmark: 5 percent of pre-tax income with a revenue sanity check.",
      metadata: {},
    },
  ],
  nodes: [
    {
      id: "audit_scope",
      title: "Audit Scope",
      subtitle: "Financial document mapping",
      operation_type: "generate",
      instruction: "Define the scope of the audit from the uploaded evidence.",
      success_criteria: ["Objective restated", "Source documents listed"],
      evaluation_ids: ["output_present"],
      priority: 10,
      status: "completed",
      verification_status: "skipped",
      verification_checks: [],
      thought_summary: "Defined the audit objective, company, and fiscal scope from the charter evidence.",
      reasoning_trace:
        "Mapped the charter evidence to a bounded audit scope, identified the audited entity and fiscal period, and carried only source-backed scope details into the node output.",
      evaluation_score: 1,
      executor_type: "llm_operator",
      executor_profile: "general",
      approval_state: {
        required_approvals: 0,
        approved_count: 0,
        pending_approvals: 0,
        requires_human_review: false,
        status: "not_required",
      },
      delegated_children: [],
      patch_history: [],
      depends_on: [],
      guarded_by: [],
      next_nodes: ["assertion_scoping"],
      evidence_refs: [demoEvidence("doc_charter")],
      inputs: {},
      output: {
        company_name: "Invisium",
        fiscal_year: "FY2026",
      },
      metadata: demoNodeMetadata(
        1,
        0,
        "frame the engagement, identify the audited entity and period, and establish the evidence boundary before any testing starts",
      ),
      latency_ms: 320,
    },
    {
      id: "assertion_scoping",
      title: "Assertion Scoping",
      subtitle: "Map significant accounts and assertions",
      operation_type: "generate",
      instruction: "Identify the accounts, assertions, and audit areas that should drive planning and downstream testing.",
      success_criteria: ["Key assertions listed", "High-risk accounts identified"],
      evaluation_ids: ["output_present"],
      priority: 15,
      status: "completed",
      verification_status: "skipped",
      verification_checks: [],
      thought_summary: "Mapped revenue, receivables, and close-process assertions into the planned audit scope.",
      reasoning_trace:
        "Used the audit charter and financial statement excerpt to identify the assertions most likely to drive material risk, especially cutoff, occurrence, and completeness for revenue.",
      evaluation_score: 0.97,
      executor_type: "llm_operator",
      executor_profile: "general",
      approval_state: {
        required_approvals: 0,
        approved_count: 0,
        pending_approvals: 0,
        requires_human_review: false,
        status: "not_required",
      },
      delegated_children: [],
      patch_history: [],
      depends_on: ["audit_scope"],
      guarded_by: [],
      next_nodes: ["materiality_assessment"],
      evidence_refs: [demoEvidence("doc_charter"), demoEvidence("doc_financials")],
      inputs: {},
      output: {
        significant_accounts: ["Revenue", "Accounts receivable"],
        significant_assertions: ["Occurrence", "Cutoff", "Completeness"],
      },
      metadata: demoNodeMetadata(
        1,
        1,
        "translate the overall engagement into specific accounts and assertions so later nodes test the right audit questions",
      ),
      latency_ms: 540,
    },
    {
      id: "materiality_assessment",
      title: "Materiality Assessment",
      subtitle: "Set planning materiality and tolerable error",
      operation_type: "analyze",
      instruction: "Compute a planning materiality view and explain how it should constrain downstream testing and findings.",
      success_criteria: ["Materiality benchmark selected", "Testing implications stated"],
      evaluation_ids: ["output_present"],
      priority: 20,
      status: "completed",
      verification_status: "skipped",
      verification_checks: [],
      thought_summary: "Established the planning materiality anchor and used it to frame the significance of revenue timing exceptions.",
      reasoning_trace:
        "Compared common audit benchmarks against the available financials, selected a conservative anchor, and converted that into a practical threshold for downstream evaluation.",
      evaluation_score: 0.98,
      executor_type: "llm_operator",
      executor_profile: "controls",
      approval_state: {
        required_approvals: 0,
        approved_count: 0,
        pending_approvals: 0,
        requires_human_review: false,
        status: "not_required",
      },
      delegated_children: [],
      patch_history: [],
      depends_on: ["assertion_scoping"],
      guarded_by: [],
      next_nodes: ["financial_data_analysis"],
      evidence_refs: [demoEvidence("doc_financials")],
      inputs: {},
      output: {
        planning_materiality: 625000,
        tolerable_error: 312500,
      },
      metadata: demoNodeMetadata(
        1,
        2,
        "set the audit significance threshold early so later findings can be judged against a defined materiality benchmark instead of ad hoc intuition",
      ),
      latency_ms: 860,
    },
    {
      id: "financial_data_analysis",
      title: "Financial Data Analysis",
      subtitle: "Extract key metrics",
      operation_type: "analyze",
      instruction: "Extract salient metrics and supporting evidence.",
      success_criteria: ["Metrics listed", "Evidence references linked"],
      evaluation_ids: ["output_present"],
      priority: 20,
      status: "completed",
      verification_status: "skipped",
      verification_checks: [],
      thought_summary: "Extracted financial metrics and materiality anchors used downstream.",
      reasoning_trace:
        "Read the financial and controls evidence, normalized the numeric fields, and selected a materiality anchor that would affect downstream control and cutoff testing.",
      evaluation_score: 0.96,
      executor_type: "agent_operator",
      executor_profile: "revenue",
      max_child_agents: 2,
      max_recursion_depth: 1,
      child_token_budget: 4000,
      delegated_summary_required: true,
      delegated_children: ["financial_data_analysis_expanded_1"],
      patch_history: ["patch_demo_scope"],
      approval_state: {
        required_approvals: 0,
        approved_count: 0,
        pending_approvals: 0,
        requires_human_review: false,
        status: "not_required",
      },
      depends_on: ["materiality_assessment"],
      guarded_by: [],
      next_nodes: ["controls_walkthrough", "compliance_check", "integrity_check"],
      evidence_refs: [demoEvidence("doc_financials"), demoEvidence("doc_controls")],
      inputs: {},
      output: {
        key_metrics: {
          revenue: 12500000,
          net_income: 610000,
          overall_materiality: 625000,
        },
      },
      metadata: demoNodeMetadata(
        1,
        3,
        "extract the core financial signals and tie them back to the materiality view so the audit can focus on the balances and trends that matter most",
      ),
      latency_ms: 2100,
    },
    {
      id: "controls_walkthrough",
      title: "Controls Walkthrough",
      subtitle: "Understand revenue and close controls",
      operation_type: "analyze",
      instruction: "Walk through the key revenue and close controls to identify where control reliance is reasonable and where substantive testing should expand.",
      success_criteria: ["Key controls summarized", "Reliance implications stated"],
      evaluation_ids: ["output_present"],
      priority: 30,
      status: "completed",
      verification_status: "skipped",
      verification_checks: [],
      thought_summary: "Mapped the control flow and identified the revenue cutoff control as the key audit dependency.",
      reasoning_trace:
        "Used the controls evidence to reconstruct the revenue and close-process control path, focusing on where timing or approval weaknesses could create misstatement risk.",
      evaluation_score: 0.95,
      executor_type: "agent_operator",
      executor_profile: "controls",
      max_child_agents: 2,
      max_recursion_depth: 1,
      child_token_budget: 3500,
      delegated_summary_required: true,
      delegated_children: ["controls_walkthrough_expanded_1"],
      patch_history: [],
      approval_state: {
        required_approvals: 0,
        approved_count: 0,
        pending_approvals: 0,
        requires_human_review: false,
        status: "not_required",
      },
      depends_on: ["financial_data_analysis"],
      guarded_by: [],
      next_nodes: ["risk_assessment"],
      evidence_refs: [demoEvidence("doc_controls")],
      inputs: {},
      output: {
        key_controls: ["Revenue cutoff review", "Month-end close approval"],
      },
      metadata: demoNodeMetadata(
        0,
        4,
        "bridge planning and testing by showing which controls matter, where reliance is possible, and where substantive work should expand",
      ),
      latency_ms: 1540,
    },
    {
      id: "compliance_check",
      title: "Compliance Check",
      subtitle: "Review policy adherence",
      operation_type: "verify",
      instruction: "Verify compliance exceptions against source evidence.",
      success_criteria: ["Verification status set", "Checks enumerated"],
      evaluation_ids: ["verification_gate"],
      priority: 30,
      status: "completed",
      verification_status: "passed",
      verification_checks: ["Revenue cutoff exceptions were traced to the supporting controls evidence."],
      thought_summary: "Compliance checks passed, with a revenue cutoff exception preserved for risk aggregation.",
      evaluation_score: 1,
      executor_type: "llm_operator",
      approval_state: {
        required_approvals: 0,
        approved_count: 0,
        pending_approvals: 0,
        requires_human_review: false,
        status: "not_required",
      },
      delegated_children: [],
      patch_history: [],
      depends_on: ["financial_data_analysis"],
      guarded_by: [],
      next_nodes: ["risk_assessment"],
      evidence_refs: [demoEvidence("doc_controls")],
      finding_records: [
        {
          id: "compliance_check_finding_1",
          text: "Revenue cutoff exceptions were identified in the controls evidence.",
          support_level: "direct",
          claim_classification: "grounded",
          evidence_refs: [demoEvidence("doc_controls")],
        },
      ],
      inputs: {},
      output: {
        conclusion: "Verification completed with exceptions logged.",
      },
      metadata: demoNodeMetadata(
        1,
        4,
        "test whether the planned audit view is still aligned with policy, cutoff, and compliance expectations before findings are aggregated",
      ),
      latency_ms: 1800,
    },
    {
      id: "integrity_check",
      title: "Integrity Check",
      subtitle: "Verify financial integrity",
      operation_type: "verify",
      instruction: "Validate structural integrity of financial statements.",
      success_criteria: ["Integrity checks completed"],
      evaluation_ids: ["verification_gate"],
      priority: 40,
      status: "completed",
      verification_status: "passed",
      verification_checks: ["Statement structure and integrity checks completed successfully."],
      thought_summary: "Integrity checks did not surface structural blockers for synthesis.",
      evaluation_score: 0.98,
      executor_type: "tool_operator",
      approval_state: {
        required_approvals: 0,
        approved_count: 0,
        pending_approvals: 0,
        requires_human_review: false,
        status: "not_required",
      },
      delegated_children: [],
      patch_history: [],
      depends_on: ["financial_data_analysis"],
      guarded_by: [],
      next_nodes: ["risk_assessment"],
      evidence_refs: [demoEvidence("doc_controls")],
      inputs: {},
      output: {
        conclusion: "Integrity checks completed.",
      },
      metadata: demoNodeMetadata(
        2,
        4,
        "confirm that the underlying records are structurally usable so downstream risk scoring is not built on broken or incomplete financial data",
      ),
      latency_ms: 1750,
    },
    {
      id: "risk_assessment",
      title: "Risk Assessment",
      subtitle: "Identify potential issues",
      operation_type: "aggregate",
      instruction: "Aggregate verified issues into a risk view.",
      success_criteria: ["Risks ranked", "Evidence linked"],
      evaluation_ids: ["output_present"],
      priority: 50,
      status: "completed",
      verification_status: "skipped",
      verification_checks: [],
      thought_summary: "Ranked the revenue cutoff exception as the dominant risk and flagged collections pressure as inferred.",
      evaluation_score: 0.93,
      executor_type: "agent_operator",
      executor_profile: "forensic",
      max_child_agents: 2,
      max_recursion_depth: 1,
      child_token_budget: 4000,
      delegated_summary_required: true,
      delegated_children: ["risk_assessment_expanded_1", "risk_assessment_expanded_2"],
      patch_history: ["patch_demo_scope"],
      approval_state: {
        required_approvals: 0,
        approved_count: 0,
        pending_approvals: 0,
        requires_human_review: false,
        status: "not_required",
      },
      depends_on: ["controls_walkthrough", "compliance_check", "integrity_check"],
      guarded_by: ["controls_walkthrough", "compliance_check", "integrity_check"],
      next_nodes: ["human_review"],
      evidence_refs: [demoEvidence("doc_controls"), demoEvidence("doc_financials")],
      finding_records: [
        {
          id: "risk_assessment_finding_1",
          text: "Revenue cutoff timing exception remains the dominant risk.",
          support_level: "direct",
          claim_classification: "grounded",
          evidence_refs: [demoEvidence("doc_controls")],
        },
        {
          id: "risk_assessment_finding_2",
          text: "Customer concentration may require additional collection analysis.",
          support_level: "inferred",
          claim_classification: "inferred",
          evidence_refs: [],
        },
      ],
      inputs: {},
      output: {
        identified_risks: [
          { title: "Revenue cutoff timing exception", severity: "medium" },
          { title: "Customer concentration and collections pressure", severity: "high" },
        ],
      },
      metadata: demoNodeMetadata(
        1,
        5,
        "combine the control walkthrough, compliance results, and integrity checks into a single ranked risk view that can support review and final synthesis",
      ),
      latency_ms: 1640,
    },
    {
      id: "human_review",
      title: "Human Review",
      subtitle: "Expert evaluation checkpoint",
      operation_type: "verify",
      instruction: "Record reviewer decision before synthesis.",
      success_criteria: ["Reviewer checkpoint captured"],
      evaluation_ids: ["verification_gate"],
      priority: 60,
      status: "completed",
      verification_status: "passed",
      verification_checks: ["Reviewer checkpoint recorded before final synthesis."],
      thought_summary: "Recorded a simulated approval gate to unblock final synthesis.",
      evaluation_score: 1,
      executor_type: "human_operator",
      approval_state: {
        required_approvals: 1,
        approved_count: 1,
        pending_approvals: 0,
        requires_human_review: true,
        status: "approved",
      },
      delegated_children: [],
      patch_history: [],
      depends_on: ["risk_assessment"],
      guarded_by: [],
      next_nodes: ["final_report_synthesis"],
      evidence_refs: [demoEvidence("doc_controls")],
      inputs: {},
      output: {
        review_mode: "simulated_auto_approval",
      },
      metadata: demoNodeMetadata(
        1,
        6,
        "simulate the partner or manager checkpoint that would normally challenge high-risk findings before the opinion is finalized",
      ),
      latency_ms: 980,
    },
    {
      id: "final_report_synthesis",
      title: "Final Report Synthesis",
      subtitle: "Produce audit opinion",
      operation_type: "synthesize",
      instruction: "Produce the final structured output and summary card.",
      success_criteria: ["Schema-compliant result", "Summary prepared"],
      evaluation_ids: ["output_present", "final_output_schema"],
      priority: 70,
      status: "completed",
      verification_status: "skipped",
      verification_checks: [],
      thought_summary: "Synthesized the final qualified opinion with linked findings and evidence.",
      reasoning_trace:
        "Merged the verified findings, ranked the revenue cutoff issue above the secondary control concerns, and drafted a review-ready conclusion with preserved evidence traceability.",
      evaluation_score: 0.94,
      executor_type: "llm_operator",
      approval_state: {
        required_approvals: 1,
        approved_count: 1,
        pending_approvals: 0,
        requires_human_review: true,
        status: "approved",
      },
      delegated_children: [],
      patch_history: [],
      depends_on: ["human_review"],
      guarded_by: ["human_review"],
      next_nodes: [],
      evidence_refs: [demoEvidence("doc_charter"), demoEvidence("doc_controls")],
      inputs: {},
      output: {
        audit_opinion: "Qualified",
      },
      metadata: demoNodeMetadata(
        1,
        7,
        "merge the planning, testing, verification, and review outputs into the final audit conclusion without losing the evidence trail",
      ),
      latency_ms: 2310,
    },
  ],
  edges: [
    { source: "audit_scope", target: "assertion_scoping", kind: "execution" },
    { source: "assertion_scoping", target: "materiality_assessment", kind: "execution" },
    { source: "materiality_assessment", target: "financial_data_analysis", kind: "execution" },
    { source: "financial_data_analysis", target: "controls_walkthrough", kind: "execution" },
    { source: "financial_data_analysis", target: "compliance_check", kind: "execution" },
    { source: "financial_data_analysis", target: "integrity_check", kind: "execution" },
    { source: "controls_walkthrough", target: "risk_assessment", kind: "execution" },
    { source: "compliance_check", target: "risk_assessment", kind: "execution" },
    { source: "integrity_check", target: "risk_assessment", kind: "execution" },
    { source: "risk_assessment", target: "human_review", kind: "execution" },
    { source: "human_review", target: "final_report_synthesis", kind: "execution" },
  ],
  execution_sequence: [
    "audit_scope",
    "assertion_scoping",
    "materiality_assessment",
    "financial_data_analysis",
    "controls_walkthrough",
    "compliance_check",
    "integrity_check",
    "risk_assessment",
    "human_review",
    "final_report_synthesis",
  ],
  evidence_graph_nodes: {
    claim_revenue_cutoff: {
      id: "claim_revenue_cutoff",
      kind: "claim",
      label: "Revenue cutoff timing exception",
      metadata: { node_id: "risk_assessment" },
    },
    evidence_controls_chunk: {
      id: "evidence_controls_chunk",
      kind: "evidence",
      label: "controls_and_compliance.txt · chunk 0",
      metadata: { document_id: "doc_controls", chunk_id: "doc_controls_chunk_0" },
    },
  },
  evidence_graph_edges: [
    {
      source: "claim_revenue_cutoff",
      target: "evidence_controls_chunk",
      relation: "supported_by",
      metadata: { support_level: "direct" },
    },
  ],
  planner_trace: {
    trace_id: "planner_demo_01",
    summary: "Built an audit planning and testing graph that starts with scope, assertions, and materiality before branching into control and verification work.",
    graph_shape_reason:
      "The graph starts with scope, assertions, and materiality so the audit plan is grounded before testing, then splits control and verification work so the final synthesis stays explicitly guarded and reviewable.",
    evidence_sources_available: [
      {
        source_id: "doc_charter",
        source_type: "upload",
        label: "audit_charter.txt",
        detail: "Task charter and fiscal scope",
      },
      {
        source_id: "doc_controls",
        source_type: "upload",
        label: "controls_and_compliance.txt",
        detail: "Controls exceptions and cutoff evidence",
      },
    ],
    web_fallback_used: false,
    web_search_queries: [],
    candidate_graph_operations: [
      {
        operation: "linear_scope_mapping",
        disposition: "selected",
        rationale: "Keeps the task scope explicit before evidence analysis begins.",
      },
      {
        operation: "branch_for_verification",
        disposition: "selected",
        rationale: "Separates validation from primary analysis so synthesis can be gated.",
      },
      {
        operation: "materiality_before_testing",
        disposition: "selected",
        rationale: "Materiality is established before testing so later findings can be judged against a consistent significance threshold.",
      },
      {
        operation: "direct_final_synthesis",
        disposition: "rejected",
        rationale: "Rejected because the audit flow needs a verification lane and reviewer checkpoint.",
      },
    ],
    node_decisions: [
      {
        node_id: "audit_scope",
        action: "added",
        reason: "Added to restate the audit objective and define the evidence boundary.",
      },
      {
        node_id: "materiality_assessment",
        action: "added",
        reason: "Added so downstream audit findings can be evaluated against a defined planning materiality threshold.",
      },
      {
        node_id: "controls_walkthrough",
        action: "branched",
        reason: "Added as a separate branch to make control reliance and walkthrough observations explicit before risk aggregation.",
      },
      {
        node_id: "compliance_check",
        action: "branched",
        reason: "Split into a verification branch to isolate policy adherence checks.",
      },
      {
        node_id: "final_report_synthesis",
        action: "merged",
        reason: "Merged the analysis, verification, and human review outputs into the final report step.",
      },
    ],
    confidence: 0.91,
    unresolved_gaps: [],
    created_at: new Date().toISOString(),
  },
  prompt_traces: [
    {
      trace_id: "trace_program_demo",
      phase: "program_synthesis",
      node_id: null,
      prompt: basePrompt,
      system_prompt: "You synthesize reasoning programs for audit workflows.",
      context: { domain: "financial audit" },
      params: { temperature: 0, top_p: 1, seed: 42 },
      request_payload: { model: "demo-provider", temperature: 0, top_p: 1, seed: 42 },
      response_payload: { program_id: "perform_a_financial_audit_for_invisium_fy_v1" },
      provider: "demo-provider",
      model_id: "demo-provider",
      model_version: "demo-provider",
      provider_fingerprint: "demo-fingerprint",
      endpoint: "https://demo-provider.local/chat/completions",
      prompt_hash: "demo-program-prompt-hash",
      response_hash: "demo-program-response-hash",
      created_at: new Date().toISOString(),
    },
    {
      trace_id: "trace_final_demo",
      phase: "node_execution",
      node_id: "final_report_synthesis",
      prompt: "Produce the final structured output and summary card.",
      system_prompt: "You are the synthesis operator.",
      context: { node_id: "final_report_synthesis" },
      params: { temperature: 0, top_p: 1, seed: 42 },
      request_payload: { model: "demo-provider", temperature: 0, top_p: 1, seed: 42 },
      response_payload: { audit_opinion: "Qualified" },
      provider: "demo-provider",
      model_id: "demo-provider",
      model_version: "demo-provider",
      provider_fingerprint: "demo-fingerprint",
      endpoint: "https://demo-provider.local/chat/completions",
      prompt_hash: "demo-final-prompt-hash",
      response_hash: "demo-final-response-hash",
      created_at: new Date().toISOString(),
    },
  ],
  graph_patch_history: [
    {
      patch_id: "patch_demo_scope",
      patch_type: "change_evidence_scope",
      target_node_id: "financial_data_analysis",
      change_reason: "Narrow demo analysis to the highest-signal controls evidence.",
      requested_by: "system-demo",
      approved_by: "system-demo",
      payload: { include_documents: ["doc_controls"] },
      resulting_program_version: "1.0.1",
      auto_rerun: true,
      applied_at: new Date().toISOString(),
    },
  ],
  graph_version_history: [
    {
      version_id: "graph_version_demo_1",
      program_version: "1.0.0",
      blueprint_hash: "demo-blueprint-hash-1",
      created_by: "system",
      reason: "Initial graph instantiation.",
      patch_id: null,
      parent_program_version: null,
      created_at: new Date().toISOString(),
    },
    {
      version_id: "graph_version_demo_2",
      program_version: "1.0.1",
      blueprint_hash: "demo-blueprint-hash-2",
      created_by: "system-demo",
      reason: "Narrow demo analysis to the highest-signal controls evidence.",
      patch_id: "patch_demo_scope",
      parent_program_version: "1.0.0",
      created_at: new Date().toISOString(),
    },
  ],
  patch_diff_history: [
    {
      patch_id: "patch_demo_scope",
      patch_type: "change_evidence_scope",
      before_program_version: "1.0.0",
      after_program_version: "1.0.1",
      before_blueprint_hash: "demo-blueprint-hash-1",
      after_blueprint_hash: "demo-blueprint-hash-2",
      added_nodes: [],
      removed_nodes: [],
      changed_nodes: ["financial_data_analysis"],
      added_edges: [],
      removed_edges: [],
      changed_policy: false,
      changed_budget: false,
      created_at: new Date().toISOString(),
    },
  ],
  trace_access_history: [
    {
      task_id: "demo-task",
      viewer_id: "dashboard-user",
      viewer_role: "reviewer",
      requested_tier: "structured_reasoning_trace",
      effective_tier: "structured_reasoning_trace",
      entry_count: 9,
      accessed_at: new Date().toISOString(),
    },
  ],
  program_blueprint: {
    program_id: "perform_a_financial_audit_for_invisium_fy_v1",
    domain: "financial audit",
  },
  output_schema_definition: {
    title: "generated_output_schema_v1",
  },
  final_output: {
    company_name: "Invisium",
    fiscal_year: "FY2026",
    audit_opinion: "Qualified",
  },
  final_summary: {
    headline: "Financial audit reasoning completed",
    verdict: "Qualified",
    key_points: [
      "Planning scope, assertions, and materiality were established before testing.",
      "Revenue cutoff timing remains the dominant exception.",
      "Verification gates passed before final synthesis.",
    ],
    metrics: [
      { label: "Domain", value: "Financial audit" },
      { label: "Opinion", value: "Qualified" },
      { label: "Findings", value: "4" },
      { label: "Materiality", value: "$625,000" },
    ],
  },
  pending_review_node_id: null,
  review_history: [],
  schema_validation_logs: [
    {
      timestamp: new Date().toISOString(),
      node_id: "final_report_synthesis",
      schema_id: "generated_output_schema_v1",
      phase: "output",
      passed: true,
      message: "Final output matched the generated schema.",
      details: {},
    },
  ],
  audit_package: {
    event_log: [
      {
        timestamp: new Date().toISOString(),
        event: "demo_mode",
        message: "Offline demo task loaded into the dashboard with expanded audit planning and testing nodes.",
      },
    ],
  },
};

export const mockHistory: TaskRunListItem[] = [
  {
    task_id: "demo-task",
    prompt: basePrompt,
    status: "completed",
    template_id: "perform_a_financial_audit_for_invisium_fy_template",
    program_id: "perform_a_financial_audit_for_invisium_fy_v1",
    domain: "financial audit",
    determinism_mode: "best_effort_deterministic",
    control_level: "operational",
    created_at: new Date().toISOString(),
    completed_at: new Date().toISOString(),
    final_summary: mockTask.final_summary,
  },
];

export const mockTemplates: TemplateSummary[] = [
  {
    template_id: "generated_from_requirements",
    name: "Generated From Requirements",
    description: "Synthesizes a reasoning graph from the requirements reference and the user prompt.",
  },
  {
    template_id: "perform_a_financial_audit_for_invisium_fy_template",
    name: "Financial Audit",
    description: "Audit-oriented template with verification gates, evidence linking, and final synthesis.",
  },
];

export const mockSkills: SkillArtifact[] = [
  {
    skill_id: "revenue_cutoff_checker",
    version: "0.1.0",
    name: "Revenue Cutoff Checker",
    description: "Validates revenue rows for premature recognition and returns flagged records as JSON.",
    language: "python",
    skill_type: "checker",
    updated_at: new Date().toISOString(),
    status: "active",
    entrypoint_filename: "main.py",
    code: [
      "import json",
      "import sys",
      "",
      "def main() -> int:",
      "    raw = sys.stdin.read() or '{}'",
      "    payload = json.loads(raw)",
      "    rows = payload.get('rows', [])",
      "    flagged = [row for row in rows if row.get('recognized_before_shipment')]",
      "    print(json.dumps({'flagged_rows': flagged, 'flagged_count': len(flagged)}))",
      "    return 0",
      "",
      "if __name__ == '__main__':",
      "    raise SystemExit(main())",
    ].join("\n"),
    test_input: JSON.stringify(
      {
        rows: [
          { invoice_id: "INV-12", recognized_before_shipment: true },
          { invoice_id: "INV-13", recognized_before_shipment: false },
        ],
      },
      null,
      2,
    ),
    notes: ["Use this on tool or agent nodes that need a quick revenue-cutoff screening pass."],
    suggested_node_executor: "tool_operator",
  },
];
