import type { TaskRunListItem, TaskRunResponse } from "./types";

const basePrompt =
  "Perform a financial audit for Invisium FY2026 using the uploaded financial statements and supporting evidence.";

export const mockTask: TaskRunResponse = {
  task_id: "demo-task",
  prompt: basePrompt,
  template_id: "perform_a_financial_audit_for_invisium_fy_template",
  program_id: "perform_a_financial_audit_for_invisium_fy_v1",
  program_version: "1.0.0",
  domain: "financial audit",
  deterministic: true,
  status: "completed",
  created_at: new Date().toISOString(),
  completed_at: new Date().toISOString(),
  source_documents: [
    {
      id: "doc_charter",
      name: "audit_charter.txt",
      media_type: "text/plain",
      storage_path: "",
      text_path: "",
      sha256: "demo",
      extracted_text: "Entity: Invisium\nFiscal year: FY2026\nAudit objective: External financial statement audit.",
      metadata: {},
    },
    {
      id: "doc_controls",
      name: "controls_and_compliance.txt",
      media_type: "text/plain",
      storage_path: "",
      text_path: "",
      sha256: "demo",
      extracted_text:
        "Revenue cutoff observations: Twelve invoices totaling USD 214500 were recognized before shipment.",
      metadata: {},
    },
  ],
  nodes: [
    {
      id: "audit_scope",
      title: "Audit Scope",
      subtitle: "Financial document mapping",
      operation_type: "generate",
      instruction: "Define the scope of the audit from the uploaded evidence.",
      success_criteria: ["Objective restated", "Source documents listed"],
      evaluation_ids: ["output_present"],
      priority: 10,
      status: "completed",
      verification_status: "skipped",
      depends_on: [],
      guarded_by: [],
      next_nodes: ["financial_data_analysis"],
      evidence_refs: ["doc_charter"],
      inputs: {},
      output: {
        company_name: "Invisium",
        fiscal_year: "FY2026",
      },
      metadata: { layout: { column: 1, row: 0 } },
      latency_ms: 320,
    },
    {
      id: "financial_data_analysis",
      title: "Financial Data Analysis",
      subtitle: "Extract key metrics",
      operation_type: "analyze",
      instruction: "Extract salient metrics and supporting evidence.",
      success_criteria: ["Metrics listed", "Evidence references linked"],
      evaluation_ids: ["output_present"],
      priority: 20,
      status: "completed",
      verification_status: "skipped",
      depends_on: ["audit_scope"],
      guarded_by: [],
      next_nodes: ["compliance_check", "integrity_check"],
      evidence_refs: ["doc_charter", "doc_controls"],
      inputs: {},
      output: {
        key_metrics: {
          revenue: 12500000,
          net_income: 610000,
          overall_materiality: 625000,
        },
      },
      metadata: { layout: { column: 1, row: 1 } },
      latency_ms: 2100,
    },
    {
      id: "compliance_check",
      title: "Compliance Check",
      subtitle: "Review policy adherence",
      operation_type: "verify",
      instruction: "Verify compliance exceptions against source evidence.",
      success_criteria: ["Verification status set", "Checks enumerated"],
      evaluation_ids: ["verification_gate"],
      priority: 30,
      status: "completed",
      verification_status: "passed",
      depends_on: ["financial_data_analysis"],
      guarded_by: [],
      next_nodes: ["risk_assessment"],
      evidence_refs: ["doc_controls"],
      inputs: {},
      output: {
        conclusion: "Verification completed with exceptions logged.",
      },
      metadata: { layout: { column: 0, row: 2 } },
      latency_ms: 1800,
    },
    {
      id: "integrity_check",
      title: "Integrity Check",
      subtitle: "Verify financial integrity",
      operation_type: "verify",
      instruction: "Validate structural integrity of financial statements.",
      success_criteria: ["Integrity checks completed"],
      evaluation_ids: ["verification_gate"],
      priority: 40,
      status: "completed",
      verification_status: "passed",
      depends_on: ["financial_data_analysis"],
      guarded_by: [],
      next_nodes: ["risk_assessment"],
      evidence_refs: ["doc_controls"],
      inputs: {},
      output: {
        conclusion: "Integrity checks completed.",
      },
      metadata: { layout: { column: 2, row: 2 } },
      latency_ms: 1750,
    },
    {
      id: "risk_assessment",
      title: "Risk Assessment",
      subtitle: "Identify potential issues",
      operation_type: "aggregate",
      instruction: "Aggregate verified issues into a risk view.",
      success_criteria: ["Risks ranked", "Evidence linked"],
      evaluation_ids: ["output_present"],
      priority: 50,
      status: "completed",
      verification_status: "skipped",
      depends_on: ["compliance_check", "integrity_check"],
      guarded_by: ["compliance_check", "integrity_check"],
      next_nodes: ["human_review"],
      evidence_refs: ["doc_controls"],
      inputs: {},
      output: {
        identified_risks: [
          { title: "Revenue cutoff timing exception", severity: "medium" },
          { title: "Customer concentration and collections pressure", severity: "high" },
        ],
      },
      metadata: { layout: { column: 1, row: 3 } },
      latency_ms: 1640,
    },
    {
      id: "human_review",
      title: "Human Review",
      subtitle: "Expert evaluation checkpoint",
      operation_type: "verify",
      instruction: "Record reviewer decision before synthesis.",
      success_criteria: ["Reviewer checkpoint captured"],
      evaluation_ids: ["verification_gate"],
      priority: 60,
      status: "completed",
      verification_status: "passed",
      depends_on: ["risk_assessment"],
      guarded_by: [],
      next_nodes: ["final_report_synthesis"],
      evidence_refs: ["doc_controls"],
      inputs: {},
      output: {
        review_mode: "simulated_auto_approval",
      },
      metadata: { layout: { column: 1, row: 4 } },
      latency_ms: 980,
    },
    {
      id: "final_report_synthesis",
      title: "Final Report Synthesis",
      subtitle: "Produce audit opinion",
      operation_type: "synthesize",
      instruction: "Produce the final structured output and summary card.",
      success_criteria: ["Schema-compliant result", "Summary prepared"],
      evaluation_ids: ["output_present", "final_output_schema"],
      priority: 70,
      status: "completed",
      verification_status: "skipped",
      depends_on: ["human_review"],
      guarded_by: ["human_review"],
      next_nodes: [],
      evidence_refs: ["doc_charter", "doc_controls"],
      inputs: {},
      output: {
        audit_opinion: "Qualified",
      },
      metadata: { layout: { column: 1, row: 5 } },
      latency_ms: 2310,
    },
  ],
  edges: [
    { source: "audit_scope", target: "financial_data_analysis", kind: "execution" },
    { source: "financial_data_analysis", target: "compliance_check", kind: "execution" },
    { source: "financial_data_analysis", target: "integrity_check", kind: "execution" },
    { source: "compliance_check", target: "risk_assessment", kind: "execution" },
    { source: "integrity_check", target: "risk_assessment", kind: "execution" },
    { source: "risk_assessment", target: "human_review", kind: "execution" },
    { source: "human_review", target: "final_report_synthesis", kind: "execution" },
  ],
  program_blueprint: {
    program_id: "perform_a_financial_audit_for_invisium_fy_v1",
    domain: "financial audit",
  },
  output_schema_definition: {
    title: "generated_output_schema_v1",
  },
  final_output: {
    company_name: "Invisium",
    fiscal_year: "FY2026",
    audit_opinion: "Qualified",
  },
  final_summary: {
    headline: "Financial audit reasoning completed",
    verdict: "Qualified",
    key_points: [
      "Revenue cutoff timing remains the dominant exception.",
      "Verification gates passed before final synthesis.",
    ],
    metrics: [
      { label: "Domain", value: "Financial audit" },
      { label: "Opinion", value: "Qualified" },
      { label: "Findings", value: "3" },
      { label: "Materiality", value: "$625,000" },
    ],
  },
  pending_review_node_id: null,
  review_history: [],
  audit_package: null,
};

export const mockHistory: TaskRunListItem[] = [
  {
    task_id: "demo-task",
    prompt: basePrompt,
    status: "completed",
    template_id: "perform_a_financial_audit_for_invisium_fy_template",
    program_id: "perform_a_financial_audit_for_invisium_fy_v1",
    domain: "financial audit",
    created_at: new Date().toISOString(),
    completed_at: new Date().toISOString(),
    final_summary: mockTask.final_summary,
  },
];
