import type { EvidenceReference, TaskRunListItem, TaskRunResponse, TemplateSummary } from "./types";

const basePrompt =
  "Perform a financial audit for Invisium FY2026 using the uploaded financial statements and supporting evidence.";

function demoEvidence(documentId: string): EvidenceReference {
  return {
    id: `${documentId}_chunk_0`,
    document_id: documentId,
    document_name: documentId,
    chunk_id: `${documentId}_chunk_0`,
    page: null,
    char_start: 0,
    char_end: 120,
    retrieval_score: 0.91,
    support_level: "direct",
    citation_mode: "direct",
    source_type: "retrieved",
    text_excerpt: "",
    metadata: {},
  };
}

export const mockTask: TaskRunResponse = {
  task_id: "demo-task",
  prompt: basePrompt,
  template_id: "perform_a_financial_audit_for_invisium_fy_template",
  program_id: "perform_a_financial_audit_for_invisium_fy_v1",
  program_version: "1.0.0",
  domain: "financial audit",
  deterministic: true,
  determinism_mode: "best_effort_deterministic",
  control_level: "operational",
  default_visibility_tier: "structured_reasoning_trace",
  model_id: "demo-provider",
  model_version: "demo-provider",
  provider_fingerprint: "demo-fingerprint",
  execution_endpoint: "https://demo-provider.local/chat/completions",
  prompt_hash: "demo-prompt-hash",
  grs_hash: "demo-grs-hash",
  execution_env_hash: "demo-env-hash",
  reproducibility_hash: "demo-repro-hash",
  status: "completed",
  created_at: new Date().toISOString(),
  completed_at: new Date().toISOString(),
  source_documents: [
    {
      id: "doc_charter",
      name: "audit_charter.txt",
      media_type: "text/plain",
      storage_path: "",
      text_path: "",
      sha256: "demo",
      extracted_text: "Entity: Invisium\nFiscal year: FY2026\nAudit objective: External financial statement audit.",
      metadata: {},
    },
    {
      id: "doc_controls",
      name: "controls_and_compliance.txt",
      media_type: "text/plain",
      storage_path: "",
      text_path: "",
      sha256: "demo",
      extracted_text:
        "Revenue cutoff observations: Twelve invoices totaling USD 214500 were recognized before shipment.",
      metadata: {},
    },
  ],
  nodes: [
    {
      id: "audit_scope",
      title: "Audit Scope",
      subtitle: "Financial document mapping",
      operation_type: "generate",
      instruction: "Define the scope of the audit from the uploaded evidence.",
      success_criteria: ["Objective restated", "Source documents listed"],
      evaluation_ids: ["output_present"],
      priority: 10,
      status: "completed",
      verification_status: "skipped",
      verification_checks: [],
      thought_summary: "Defined the audit objective, company, and fiscal scope from the charter evidence.",
      evaluation_score: 1,
      executor_type: "llm_operator",
      executor_profile: "general",
      approval_state: {
        required_approvals: 0,
        approved_count: 0,
        pending_approvals: 0,
        requires_human_review: false,
        status: "not_required",
      },
      delegated_children: [],
      patch_history: [],
      depends_on: [],
      guarded_by: [],
      next_nodes: ["financial_data_analysis"],
      evidence_refs: [demoEvidence("doc_charter")],
      inputs: {},
      output: {
        company_name: "Invisium",
        fiscal_year: "FY2026",
      },
      metadata: { layout: { column: 1, row: 0 } },
      latency_ms: 320,
    },
    {
      id: "financial_data_analysis",
      title: "Financial Data Analysis",
      subtitle: "Extract key metrics",
      operation_type: "analyze",
      instruction: "Extract salient metrics and supporting evidence.",
      success_criteria: ["Metrics listed", "Evidence references linked"],
      evaluation_ids: ["output_present"],
      priority: 20,
      status: "completed",
      verification_status: "skipped",
      verification_checks: [],
      thought_summary: "Extracted financial metrics and materiality anchors used downstream.",
      evaluation_score: 0.96,
      executor_type: "agent_operator",
      executor_profile: "revenue",
      max_child_agents: 2,
      max_recursion_depth: 1,
      child_token_budget: 4000,
      delegated_summary_required: true,
      delegated_children: ["financial_data_analysis_expanded_1"],
      patch_history: ["patch_demo_scope"],
      approval_state: {
        required_approvals: 0,
        approved_count: 0,
        pending_approvals: 0,
        requires_human_review: false,
        status: "not_required",
      },
      depends_on: ["audit_scope"],
      guarded_by: [],
      next_nodes: ["compliance_check", "integrity_check"],
      evidence_refs: [demoEvidence("doc_charter"), demoEvidence("doc_controls")],
      inputs: {},
      output: {
        key_metrics: {
          revenue: 12500000,
          net_income: 610000,
          overall_materiality: 625000,
        },
      },
      metadata: { layout: { column: 1, row: 1 } },
      latency_ms: 2100,
    },
    {
      id: "compliance_check",
      title: "Compliance Check",
      subtitle: "Review policy adherence",
      operation_type: "verify",
      instruction: "Verify compliance exceptions against source evidence.",
      success_criteria: ["Verification status set", "Checks enumerated"],
      evaluation_ids: ["verification_gate"],
      priority: 30,
      status: "completed",
      verification_status: "passed",
      verification_checks: ["Revenue cutoff exceptions were traced to the supporting controls evidence."],
      thought_summary: "Compliance checks passed, with a revenue cutoff exception preserved for risk aggregation.",
      evaluation_score: 1,
      executor_type: "llm_operator",
      approval_state: {
        required_approvals: 0,
        approved_count: 0,
        pending_approvals: 0,
        requires_human_review: false,
        status: "not_required",
      },
      delegated_children: [],
      patch_history: [],
      depends_on: ["financial_data_analysis"],
      guarded_by: [],
      next_nodes: ["risk_assessment"],
      evidence_refs: [demoEvidence("doc_controls")],
      finding_records: [
        {
          id: "compliance_check_finding_1",
          text: "Revenue cutoff exceptions were identified in the controls evidence.",
          support_level: "direct",
          claim_classification: "grounded",
          evidence_refs: [demoEvidence("doc_controls")],
        },
      ],
      inputs: {},
      output: {
        conclusion: "Verification completed with exceptions logged.",
      },
      metadata: { layout: { column: 0, row: 2 } },
      latency_ms: 1800,
    },
    {
      id: "integrity_check",
      title: "Integrity Check",
      subtitle: "Verify financial integrity",
      operation_type: "verify",
      instruction: "Validate structural integrity of financial statements.",
      success_criteria: ["Integrity checks completed"],
      evaluation_ids: ["verification_gate"],
      priority: 40,
      status: "completed",
      verification_status: "passed",
      verification_checks: ["Statement structure and integrity checks completed successfully."],
      thought_summary: "Integrity checks did not surface structural blockers for synthesis.",
      evaluation_score: 0.98,
      executor_type: "tool_operator",
      approval_state: {
        required_approvals: 0,
        approved_count: 0,
        pending_approvals: 0,
        requires_human_review: false,
        status: "not_required",
      },
      delegated_children: [],
      patch_history: [],
      depends_on: ["financial_data_analysis"],
      guarded_by: [],
      next_nodes: ["risk_assessment"],
      evidence_refs: [demoEvidence("doc_controls")],
      inputs: {},
      output: {
        conclusion: "Integrity checks completed.",
      },
      metadata: { layout: { column: 2, row: 2 } },
      latency_ms: 1750,
    },
    {
      id: "risk_assessment",
      title: "Risk Assessment",
      subtitle: "Identify potential issues",
      operation_type: "aggregate",
      instruction: "Aggregate verified issues into a risk view.",
      success_criteria: ["Risks ranked", "Evidence linked"],
      evaluation_ids: ["output_present"],
      priority: 50,
      status: "completed",
      verification_status: "skipped",
      verification_checks: [],
      thought_summary: "Ranked the revenue cutoff exception as the dominant risk and flagged collections pressure as inferred.",
      evaluation_score: 0.93,
      executor_type: "agent_operator",
      executor_profile: "forensic",
      max_child_agents: 2,
      max_recursion_depth: 1,
      child_token_budget: 4000,
      delegated_summary_required: true,
      delegated_children: ["risk_assessment_expanded_1", "risk_assessment_expanded_2"],
      patch_history: ["patch_demo_scope"],
      approval_state: {
        required_approvals: 0,
        approved_count: 0,
        pending_approvals: 0,
        requires_human_review: false,
        status: "not_required",
      },
      depends_on: ["compliance_check", "integrity_check"],
      guarded_by: ["compliance_check", "integrity_check"],
      next_nodes: ["human_review"],
      evidence_refs: [demoEvidence("doc_controls")],
      finding_records: [
        {
          id: "risk_assessment_finding_1",
          text: "Revenue cutoff timing exception remains the dominant risk.",
          support_level: "direct",
          claim_classification: "grounded",
          evidence_refs: [demoEvidence("doc_controls")],
        },
        {
          id: "risk_assessment_finding_2",
          text: "Customer concentration may require additional collection analysis.",
          support_level: "inferred",
          claim_classification: "inferred",
          evidence_refs: [],
        },
      ],
      inputs: {},
      output: {
        identified_risks: [
          { title: "Revenue cutoff timing exception", severity: "medium" },
          { title: "Customer concentration and collections pressure", severity: "high" },
        ],
      },
      metadata: { layout: { column: 1, row: 3 } },
      latency_ms: 1640,
    },
    {
      id: "human_review",
      title: "Human Review",
      subtitle: "Expert evaluation checkpoint",
      operation_type: "verify",
      instruction: "Record reviewer decision before synthesis.",
      success_criteria: ["Reviewer checkpoint captured"],
      evaluation_ids: ["verification_gate"],
      priority: 60,
      status: "completed",
      verification_status: "passed",
      verification_checks: ["Reviewer checkpoint recorded before final synthesis."],
      thought_summary: "Recorded a simulated approval gate to unblock final synthesis.",
      evaluation_score: 1,
      executor_type: "human_operator",
      approval_state: {
        required_approvals: 1,
        approved_count: 1,
        pending_approvals: 0,
        requires_human_review: true,
        status: "approved",
      },
      delegated_children: [],
      patch_history: [],
      depends_on: ["risk_assessment"],
      guarded_by: [],
      next_nodes: ["final_report_synthesis"],
      evidence_refs: [demoEvidence("doc_controls")],
      inputs: {},
      output: {
        review_mode: "simulated_auto_approval",
      },
      metadata: { layout: { column: 1, row: 4 } },
      latency_ms: 980,
    },
    {
      id: "final_report_synthesis",
      title: "Final Report Synthesis",
      subtitle: "Produce audit opinion",
      operation_type: "synthesize",
      instruction: "Produce the final structured output and summary card.",
      success_criteria: ["Schema-compliant result", "Summary prepared"],
      evaluation_ids: ["output_present", "final_output_schema"],
      priority: 70,
      status: "completed",
      verification_status: "skipped",
      verification_checks: [],
      thought_summary: "Synthesized the final qualified opinion with linked findings and evidence.",
      evaluation_score: 0.94,
      executor_type: "llm_operator",
      approval_state: {
        required_approvals: 1,
        approved_count: 1,
        pending_approvals: 0,
        requires_human_review: true,
        status: "approved",
      },
      delegated_children: [],
      patch_history: [],
      depends_on: ["human_review"],
      guarded_by: ["human_review"],
      next_nodes: [],
      evidence_refs: [demoEvidence("doc_charter"), demoEvidence("doc_controls")],
      inputs: {},
      output: {
        audit_opinion: "Qualified",
      },
      metadata: { layout: { column: 1, row: 5 } },
      latency_ms: 2310,
    },
  ],
  edges: [
    { source: "audit_scope", target: "financial_data_analysis", kind: "execution" },
    { source: "financial_data_analysis", target: "compliance_check", kind: "execution" },
    { source: "financial_data_analysis", target: "integrity_check", kind: "execution" },
    { source: "compliance_check", target: "risk_assessment", kind: "execution" },
    { source: "integrity_check", target: "risk_assessment", kind: "execution" },
    { source: "risk_assessment", target: "human_review", kind: "execution" },
    { source: "human_review", target: "final_report_synthesis", kind: "execution" },
  ],
  execution_sequence: [
    "audit_scope",
    "financial_data_analysis",
    "compliance_check",
    "integrity_check",
    "risk_assessment",
    "human_review",
    "final_report_synthesis",
  ],
  evidence_graph_nodes: {
    claim_revenue_cutoff: {
      id: "claim_revenue_cutoff",
      kind: "claim",
      label: "Revenue cutoff timing exception",
      metadata: { node_id: "risk_assessment" },
    },
    evidence_controls_chunk: {
      id: "evidence_controls_chunk",
      kind: "evidence",
      label: "controls_and_compliance.txt · chunk 0",
      metadata: { document_id: "doc_controls", chunk_id: "doc_controls_chunk_0" },
    },
  },
  evidence_graph_edges: [
    {
      source: "claim_revenue_cutoff",
      target: "evidence_controls_chunk",
      relation: "supported_by",
      metadata: { support_level: "direct" },
    },
  ],
  prompt_traces: [
    {
      trace_id: "trace_program_demo",
      phase: "program_synthesis",
      node_id: null,
      prompt: basePrompt,
      system_prompt: "You synthesize reasoning programs for audit workflows.",
      context: { domain: "financial audit" },
      params: { temperature: 0, top_p: 1, seed: 42 },
      request_payload: { model: "demo-provider", temperature: 0, top_p: 1, seed: 42 },
      response_payload: { program_id: "perform_a_financial_audit_for_invisium_fy_v1" },
      provider: "demo-provider",
      model_id: "demo-provider",
      model_version: "demo-provider",
      provider_fingerprint: "demo-fingerprint",
      endpoint: "https://demo-provider.local/chat/completions",
      prompt_hash: "demo-program-prompt-hash",
      response_hash: "demo-program-response-hash",
      created_at: new Date().toISOString(),
    },
    {
      trace_id: "trace_final_demo",
      phase: "node_execution",
      node_id: "final_report_synthesis",
      prompt: "Produce the final structured output and summary card.",
      system_prompt: "You are the synthesis operator.",
      context: { node_id: "final_report_synthesis" },
      params: { temperature: 0, top_p: 1, seed: 42 },
      request_payload: { model: "demo-provider", temperature: 0, top_p: 1, seed: 42 },
      response_payload: { audit_opinion: "Qualified" },
      provider: "demo-provider",
      model_id: "demo-provider",
      model_version: "demo-provider",
      provider_fingerprint: "demo-fingerprint",
      endpoint: "https://demo-provider.local/chat/completions",
      prompt_hash: "demo-final-prompt-hash",
      response_hash: "demo-final-response-hash",
      created_at: new Date().toISOString(),
    },
  ],
  graph_patch_history: [
    {
      patch_id: "patch_demo_scope",
      patch_type: "change_evidence_scope",
      target_node_id: "financial_data_analysis",
      change_reason: "Narrow demo analysis to the highest-signal controls evidence.",
      requested_by: "system-demo",
      approved_by: "system-demo",
      payload: { include_documents: ["doc_controls"] },
      resulting_program_version: "1.0.1",
      auto_rerun: true,
      applied_at: new Date().toISOString(),
    },
  ],
  graph_version_history: [
    {
      version_id: "graph_version_demo_1",
      program_version: "1.0.0",
      blueprint_hash: "demo-blueprint-hash-1",
      created_by: "system",
      reason: "Initial graph instantiation.",
      patch_id: null,
      parent_program_version: null,
      created_at: new Date().toISOString(),
    },
    {
      version_id: "graph_version_demo_2",
      program_version: "1.0.1",
      blueprint_hash: "demo-blueprint-hash-2",
      created_by: "system-demo",
      reason: "Narrow demo analysis to the highest-signal controls evidence.",
      patch_id: "patch_demo_scope",
      parent_program_version: "1.0.0",
      created_at: new Date().toISOString(),
    },
  ],
  patch_diff_history: [
    {
      patch_id: "patch_demo_scope",
      patch_type: "change_evidence_scope",
      before_program_version: "1.0.0",
      after_program_version: "1.0.1",
      before_blueprint_hash: "demo-blueprint-hash-1",
      after_blueprint_hash: "demo-blueprint-hash-2",
      added_nodes: [],
      removed_nodes: [],
      changed_nodes: ["financial_data_analysis"],
      added_edges: [],
      removed_edges: [],
      changed_policy: false,
      changed_budget: false,
      created_at: new Date().toISOString(),
    },
  ],
  trace_access_history: [
    {
      task_id: "demo-task",
      viewer_id: "dashboard-user",
      viewer_role: "reviewer",
      requested_tier: "structured_reasoning_trace",
      effective_tier: "structured_reasoning_trace",
      entry_count: 7,
      accessed_at: new Date().toISOString(),
    },
  ],
  program_blueprint: {
    program_id: "perform_a_financial_audit_for_invisium_fy_v1",
    domain: "financial audit",
  },
  output_schema_definition: {
    title: "generated_output_schema_v1",
  },
  final_output: {
    company_name: "Invisium",
    fiscal_year: "FY2026",
    audit_opinion: "Qualified",
  },
  final_summary: {
    headline: "Financial audit reasoning completed",
    verdict: "Qualified",
    key_points: [
      "Revenue cutoff timing remains the dominant exception.",
      "Verification gates passed before final synthesis.",
    ],
    metrics: [
      { label: "Domain", value: "Financial audit" },
      { label: "Opinion", value: "Qualified" },
      { label: "Findings", value: "3" },
      { label: "Materiality", value: "$625,000" },
    ],
  },
  pending_review_node_id: null,
  review_history: [],
  schema_validation_logs: [
    {
      timestamp: new Date().toISOString(),
      node_id: "final_report_synthesis",
      schema_id: "generated_output_schema_v1",
      phase: "output",
      passed: true,
      message: "Final output matched the generated schema.",
      details: {},
    },
  ],
  audit_package: {
    event_log: [
      {
        timestamp: new Date().toISOString(),
        event: "demo_mode",
        message: "Offline demo task loaded into the dashboard.",
      },
    ],
  },
};

export const mockHistory: TaskRunListItem[] = [
  {
    task_id: "demo-task",
    prompt: basePrompt,
    status: "completed",
    template_id: "perform_a_financial_audit_for_invisium_fy_template",
    program_id: "perform_a_financial_audit_for_invisium_fy_v1",
    domain: "financial audit",
    determinism_mode: "best_effort_deterministic",
    control_level: "operational",
    created_at: new Date().toISOString(),
    completed_at: new Date().toISOString(),
    final_summary: mockTask.final_summary,
  },
];

export const mockTemplates: TemplateSummary[] = [
  {
    template_id: "generated_from_requirements",
    name: "Generated From Requirements",
    description: "Synthesizes a reasoning graph from the requirements reference and the user prompt.",
  },
  {
    template_id: "perform_a_financial_audit_for_invisium_fy_template",
    name: "Financial Audit",
    description: "Audit-oriented template with verification gates, evidence linking, and final synthesis.",
  },
];
